//! Extension-host RPC proxy identifiers.
//!
//! On the wire an RPC request names its target actor by a **one-byte number**, not by name
//! (`rpcProtocol.ts` `_requestJSONArgs`: `result.writeUInt8(rpcId)`). The number is
//! `ProxyIdentifier.nid`, assigned by a global counter in **declaration order** of the
//! `createProxyIdentifier(...)` calls (`proxyIdentifier.ts` L42: `this.nid = (++ProxyIdentifier.count)`).
//! At the pinned commit those calls exist only in `extHost.protocol.ts` (`MainContext` L4046-4134,
//! then `ExtHostContext` L4136-4218), so the numbering is fully determined by that file — and
//! **any insertion upstream shifts every later id**. This is the single most fragile fact in the
//! whole connection; see `docs/design/EDITOR-CONNECTION.md` §5.
//!
//! The table below is generated by `crates/editor-conn/scripts/gen_rpc_ids.sh` from Code-OSS
//! [`crate::PINNED_VERSION`] (commit [`PINNED_COMMIT`], the tag in `build/ose/VERSION`). CI regenerates
//! it at that tag and fails on any difference. Regenerate it for every Code-OSS bump; at runtime
//! [`crate::handshake::verify_server`] refuses servers whose `GET /version` is another commit.

/// The Code-OSS commit [`PROXY_IDS`] was generated from (re-export of the crate-wide pin).
pub use crate::PINNED_COMMIT;

/// `PROXY_IDS[nid - 1]` is the identifier name with `nid`.
pub const PROXY_IDS: &[&str] = &[
    "MainThreadAuthentication", // 1
    "MainThreadBulkEdits", // 2
    "MainThreadLanguageModels", // 3
    "MainThreadEmbeddings", // 4
    "MainThreadChatAgents2", // 5
    "MainThreadCodeMapper", // 6
    "MainThreadLanguageModelTools", // 7
    "MainThreadGitExtension", // 8
    "MainThreadClipboard", // 9
    "MainThreadCommands", // 10
    "MainThreadComments", // 11
    "MainThreadConfiguration", // 12
    "MainThreadConsole", // 13
    "MainThreadDebugService", // 14
    "MainThreadDecorations", // 15
    "MainThreadDiagnostics", // 16
    "MainThreadDialogs", // 17
    "MainThreadDocuments", // 18
    "MainThreadDocumentContentProviders", // 19
    "MainThreadTextEditors", // 20
    "MainThreadEditorInsets", // 21
    "MainThreadEditorTabs", // 22
    "MainThreadErrors", // 23
    "MainThreadTreeViews", // 24
    "MainThreadDownloadService", // 25
    "MainThreadLanguageFeatures", // 26
    "MainThreadLanguages", // 27
    "MainThreadLogger", // 28
    "MainThreadMessageService", // 29
    "MainThreadOutputService", // 30
    "MainThreadProgress", // 31
    "MainThreadQuickDiff", // 32
    "MainThreadAgentEditorComments", // 33
    "MainThreadDocumentDiff", // 34
    "MainThreadQuickOpen", // 35
    "MainThreadStatusBar", // 36
    "MainThreadSecretState", // 37
    "MainThreadStorage", // 38
    "MainThreadSpeech", // 39
    "MainThreadTelemetry", // 40
    "MainThreadMeteredConnection", // 41
    "MainThreadTerminalService", // 42
    "MainThreadTerminalShellIntegration", // 43
    "MainThreadWebviews", // 44
    "MainThreadWebviewPanels", // 45
    "MainThreadWebviewViews", // 46
    "MainThreadCustomEditors", // 47
    "MainThreadUrls", // 48
    "MainThreadUriOpeners", // 49
    "MainThreadProfileContentHandlers", // 50
    "MainThreadWorkspace", // 51
    "MainThreadFileSystem", // 52
    "MainThreadFileSystemEventService", // 53
    "MainThreadExtensionService", // 54
    "MainThreadSCM", // 55
    "MainThreadSearch", // 56
    "MainThreadShare", // 57
    "MainThreadTask", // 58
    "MainThreadWindow", // 59
    "MainThreadPower", // 60
    "MainThreadLabelService", // 61
    "MainThreadNotebook", // 62
    "MainThreadNotebookDocuments", // 63
    "MainThreadNotebookEditors", // 64
    "MainThreadNotebookKernels", // 65
    "MainThreadNotebookRenderers", // 66
    "MainThreadInteractive", // 67
    "MainThreadTheming", // 68
    "MainThreadTunnelService", // 69
    "MainThreadManagedSockets", // 70
    "MainThreadBrowserTunnelProxy", // 71
    "MainThreadTimeline", // 72
    "MainThreadTesting", // 73
    "MainThreadLocalization", // 74
    "MainThreadMcp", // 75
    "MainThreadAiRelatedInformation", // 76
    "MainThreadAiEmbeddingVector", // 77
    "MainThreadChatStatus", // 78
    "MainThreadChatQuota", // 79
    "MainThreadChatInputNotification", // 80
    "MainThreadAiSettingsSearch", // 81
    "MainThreadDataChannels", // 82
    "MainThreadChatSessions", // 83
    "MainThreadChatOutputRenderer", // 84
    "MainThreadChatContext", // 85
    "MainThreadChatDebug", // 86
    "MainThreadBrowsers", // 87
    "ExtHostCodeMapper", // 88
    "ExtHostCommands", // 89
    "ExtHostConfiguration", // 90
    "ExtHostDiagnostics", // 91
    "ExtHostDebugService", // 92
    "ExtHostDecorations", // 93
    "ExtHostDocumentsAndEditors", // 94
    "ExtHostDocuments", // 95
    "ExtHostDocumentContentProviders", // 96
    "ExtHostDocumentSaveParticipant", // 97
    "ExtHostEditors", // 98
    "ExtHostTreeViews", // 99
    "ExtHostFileSystem", // 100
    "ExtHostFileSystemInfo", // 101
    "ExtHostFileSystemEventService", // 102
    "ExtHostLanguages", // 103
    "ExtHostLanguageFeatures", // 104
    "ExtHostQuickOpen", // 105
    "ExtHostQuickDiff", // 106
    "ExtHostAgentEditorComments", // 107
    "ExtHostStatusBar", // 108
    "ExtHostShare", // 109
    "ExtHostExtensionService", // 110
    "ExtHostLogLevelServiceShape", // 111
    "ExtHostTerminalService", // 112
    "ExtHostTerminalShellIntegration", // 113
    "ExtHostSCM", // 114
    "ExtHostSearch", // 115
    "ExtHostTask", // 116
    "ExtHostWorkspace", // 117
    "ExtHostWindow", // 118
    "ExtHostPower", // 119
    "ExtHostWebviews", // 120
    "ExtHostWebviewPanels", // 121
    "ExtHostCustomEditors", // 122
    "ExtHostWebviewViews", // 123
    "ExtHostEditorInsets", // 124
    "ExtHostEditorTabs", // 125
    "ExtHostProgress", // 126
    "ExtHostComments", // 127
    "ExtHostSecretState", // 128
    "ExtHostStorage", // 129
    "ExtHostUrls", // 130
    "ExtHostUriOpeners", // 131
    "ExtHostChatOutputRenderer", // 132
    "ExtHostProfileContentHandlers", // 133
    "ExtHostOutputService", // 134
    "ExtHostLabelService", // 135
    "ExtHostNotebook", // 136
    "ExtHostNotebookDocuments", // 137
    "ExtHostNotebookEditors", // 138
    "ExtHostNotebookKernels", // 139
    "ExtHostNotebookRenderers", // 140
    "ExtHostNotebookDocumentSaveParticipant", // 141
    "ExtHostInteractive", // 142
    "ExtHostChatAgents2", // 143
    "ExtHostLanguageModelTools", // 144
    "ExtHostChatProvider", // 145
    "ExtHostChatContext", // 146
    "ExtHostChatDebug", // 147
    "ExtHostSpeech", // 148
    "ExtHostEmbeddings", // 149
    "ExtHostAiRelatedInformation", // 150
    "ExtHostAiEmbeddingVector", // 151
    "ExtHostAiSettingsSearch", // 152
    "ExtHostTheming", // 153
    "ExtHostTunnelService", // 154
    "ExtHostManagedSockets", // 155
    "ExtHostBrowserTunnelProxy", // 156
    "ExtHostAuthentication", // 157
    "ExtHostTimeline", // 158
    "ExtHostTesting", // 159
    "ExtHostTelemetry", // 160
    "ExtHostMeteredConnection", // 161
    "ExtHostLocalization", // 162
    "ExtHostMcp", // 163
    "ExtHostDataChannels", // 164
    "ExtHostChatSessions", // 165
    "ExtHostChatQuota", // 166
    "ExtHostGitExtension", // 167
    "ExtHostBrowsers", // 168
];

/// The numeric id of a proxy identifier by name (`"ExtHostDocuments"` → 95 at the pinned commit).
pub fn id_of(name: &str) -> Option<u8> {
    PROXY_IDS.iter().position(|n| *n == name).map(|i| (i + 1) as u8)
}

/// The name of a numeric id.
pub fn name_of(id: u8) -> Option<&'static str> {
    (id as usize).checked_sub(1).and_then(|i| PROXY_IDS.get(i)).copied()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ids_fit_in_a_byte_and_are_unique() {
        assert!(PROXY_IDS.len() <= 255);
        let mut seen = std::collections::HashSet::new();
        for n in PROXY_IDS {
            assert!(seen.insert(*n), "duplicate {n}");
        }
    }

    /// Spot checks computed by hand from extHost.protocol.ts at the pinned commit.
    #[test]
    fn pinned_ids() {
        assert_eq!(id_of("MainThreadAuthentication"), Some(1));
        assert_eq!(id_of("MainThreadCommands"), Some(10));
        assert_eq!(id_of("MainThreadConfiguration"), Some(12));
        assert_eq!(id_of("MainThreadDiagnostics"), Some(16));
        assert_eq!(id_of("MainThreadDocuments"), Some(18));
        assert_eq!(id_of("MainThreadLanguageFeatures"), Some(26));
        assert_eq!(id_of("MainThreadStorage"), Some(38));
        assert_eq!(id_of("MainThreadExtensionService"), Some(54));
        assert_eq!(id_of("MainThreadBrowsers"), Some(87));
        assert_eq!(id_of("ExtHostCommands"), Some(89));
        assert_eq!(id_of("ExtHostConfiguration"), Some(90));
        assert_eq!(id_of("ExtHostDocumentsAndEditors"), Some(94));
        assert_eq!(id_of("ExtHostDocuments"), Some(95));
        assert_eq!(id_of("ExtHostLanguageFeatures"), Some(104));
        assert_eq!(id_of("ExtHostExtensionService"), Some(110));
        assert_eq!(id_of("ExtHostWorkspace"), Some(117));
        assert_eq!(id_of("ExtHostBrowsers"), Some(168));
        assert_eq!(name_of(0), None);
        assert_eq!(name_of(95), Some("ExtHostDocuments"));
    }
}
